### ISSUE TITLE
Cómo Actualizar el Laravel para el 5.4?

### ISSUE THREAD

**Issue by miscapu** [EspecializaTi/vagrant-setup-php#3]
Cuando intento instalar el laravel 5.4 me informa de que no tengo posibilidades ya que necesito otro php más actual. Queria instalar el 7.0.10
He intentado modificarlo desde el archivo setup.sh y me salen multiples errores al iniciar la descarga.

**Comment by joaorobertopb** [comment]
Adicionado suporte para o php7.1.
