### ISSUE TITLE
Lentidão na atualização do sistema e no uso do git.

### ISSUE THREAD

**Issue by jedsonmelo** [EspecializaTi/vagrant-setup-php#5]
Boa noite pessoal, gostaria de saber se é normal ou se algum problema com minha instalação do vagrant... As requisições do sistema demoram de 5 a 10 segundos, para ser concluida, isso não é normal já que trabalho com o mesmo sistema em ambiente lamp no proprio linux e não demora tanto e além disso demora uns 10min pra eu da um simples git status utilizando ssh com o putty. Sabem qual o problema? não mudei nada nas configurações... vi pesquisando um pouco que o desempenho melhora com a utilização de NFS, só que não sei como funciona :(

**Comment by joaorobertopb** [comment]
Olá,  @jedsonmelo .
Infelizmente essa lentidão acontece no compartilhamento de arquivos entre a máquina host ( windows ) e a máquina guest ( linux ), no vagrant com as configurações default, o compartilhamento é feito pelo hypervisor ( que neste caso é o Virtualbox ).. o NFS ajuda sim, porém isso não funciona no windows...

**Comment by jedsonmelo** [comment]
@joaorobertopb a, entendi veio. Então não vou conseguir utilizar o vagrant no windows, é uma otima ferramenta mas não da pra desenvolver em um ambiente tão lento. Vlw.
