### ISSUE TITLE
Dúvida: Atualizar o PHP para 5.6

### ISSUE THREAD

**Issue by larbous** [EspecializaTi/vagrant-setup-php#6]
Olá Caros,

Usei este script numa das versões anterior que instalava a versão 5.5.9 do php e gostaria de atualizar. Minha dúvida é: se eu apenas alterar o setup.sh para esta nova versão e rodar o vagrant up, o servidor vai atualizar automaticamente? 

Preciso atualizar mas sem perder o que já foi configurado em termos de mysql e sites.

Ou se puderem me indicar algum tutorial para eu seguir. Procurei mas não encontrei na relevante.

Obrigado.

**Comment by FabaoAnalista** [comment]
Cara pelo que sei para atualizar configurações você precisa de rodar o comando vagrant reload --provision após atualizar os arquivos de configurações .

**Comment by larbous** [comment]
Fera, perfeito. Eu só copie o conteúdo atualizado para o setup.sh e rodei conforme sua sugestão e atualizou tudo sem perder as bases mysql ou configurações de hosts.
Obrigado pela ajuda.
