### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by elinardo10** [EspecializaTi/vagrant-setup-php#7]
Cara já tentei de tudo rodar o npm run dev para startar serviços de vue ou mesmo o laravel.mix...
Até abri a discussão lá no face. Veja ai cara essa solução nesse pacote, pois é ele que eu uso. valeu.

**Comment by carlosfgti** [comment]
Acho que essa issue foi aberta no local errado. :P

Preciso de detalhes do erro pra te ajudar.
Se você se refere a esse projeto na descrição tem o passo a passo como rodar o projeto: https://github.com/carlosfgti/laravel-com-vue-exemplo
Se não funcionar é algo relacionado a algum problema ao ambiente, e não ao projeto, porque funcionou para muitas outras pessoas.

Sobre a discussão que abriu no Facebook dá continuidade nela, até resolver. Só interagir lá que responderemos!

Conta comigo. Abs!
